#!/command/with-contenv bash

source /assets/functions/00-container
PROCESS_NAME="lsyncd"

check_container_initialized
check_service_initialized init
liftoff

print_start "Starting lsyncd "
exec s6-setuidgid root lsyncd -nodaemon -insist /config/lsyncd.lua
