## Drupal Boost map directives (http-level, included via server.conf.d)
map $http_user_agent $is_bot {
    default  '';
    ~*crawl|goog|yahoo|yandex|spider|bot|tracker|click|parser is_bot;
}
map $request_uri $stripped_uri {
    ~^(.*[^/])/$ $1;
    default $request_uri;
}
map $http_x_boost_warm$http_cookie $drupal_boost_try_files {
    default /sites/default/files/boost/${host}${stripped_uri}.html;
    ~Drupal.visitor.DRUPAL_UID "";
    ~^1 "";
}
map $http_x_boost_warm$http_cookie $drupal_boost_try_files_homepage {
    default /sites/default/files/boost/${host}/index.html;
    ~Drupal.visitor.DRUPAL_UID "";
    ~^1 "";
}
map $http_x_boost_warm$http_cookie $drupal_boost_subdir_try_files_homepage {
    default /sites/default/files/boost/${host}${stripped_uri}/index.html;
    ~Drupal.visitor.DRUPAL_UID "";
    ~^1 "";
}
map $http_x_boost_warm$http_cookie $drupal_boost_header {
    default /sites/default/files/boost/${host}${stripped_uri}.html;
    ~Drupal.visitor.DRUPAL_UID "";
    ~^1 "";
}
map $request_method $drupal_boost_try_final {
    GET    $drupal_boost_try_files;
    HEAD   $drupal_boost_try_files;
    default '';
}
map $request_method $drupal_boost_try_homepage_final {
    GET    $drupal_boost_try_files_homepage;
    HEAD   $drupal_boost_try_files_homepage;
    default '';
}