version: "3"
services:
  nginx-proxy:
    image: "nginx-proxy/nginx-proxy"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      #- "./nginx/custom.conf:/etc/nginx/conf.d/my_custom_proxy_settings.conf"
    ports:
      - "80:80"
    environment:
      - HTTPS_METHOD=nohttps
      - HSTS=off
    networks:
      - frontend

  drupal-example:
    image: "sparkpos/docker-nginx-php:7.4-alpine"
    volumes:
      - ~/your-code:/var/www/html 
    environment:
      - VIRTUAL_HOST=example.dev,example.local
      - DRUPAL_WEB_ROOT=web
      - HTTP_HEADER_X_FRAME_OPTIONS="allow-from example.com"
      - "HTTP_HEADER_X_CONTENT_SECURITY_POLICY=default-src 'self' data: 'unsafe-inline' 'unsafe-eval' *.google.com *.baidu.com unpkg.com *.gstatic.com *.googleapis.com;"
      # Blow environment variable are for using drush in project
      # - PATH=/var/www/html/bin:/var/www/html/vendor/bin:$PATH
    hostname: "example.docker"
    networks:
      - frontend
      - backend

  mysql:
    image: mariadb:10.5
    ports:
      - "3306:3306"
    volumes:
      - ~/storage/mariadb:/var/lib/mysql
      - ./etc/mysql/my.cnf:/etc/my.cnf
    privileged: true
    environment:
      TZ: 'Asia/Shanghai'
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_ROOT_HOST: "%"
    networks:
      - backend

networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
  backend:
    driver: bridge
    ipam:
      driver: default
