#!/command/with-contenv bash
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
SERVICE_NAME="nginx"

prepare_service single
check_container_initialized
check_service_initialized init
liftoff

call nginx_run