#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service 30-lsyncd
PROCESS_NAME="lsyncd"

if var_true "${ENABLE_LSYNCD}" ; then    
	if [ -n "$LSYNCD_TARGET_RSYNCD_PASSWORD" ]; then
    	echo "$LSYNCD_TARGET_RSYNCD_PASSWORD" > /config/rsyncd.secrets
		chmod 0400 /config/rsyncd.secrets
	fi

	print_notice "Enabling Lsyncd for file sync"
else
	service_stop 30-lsyncd
fi

liftoff