#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service 30-lsyncd
PROCESS_NAME="lsyncd"

if var_true "${ENABLE_LSYNCD}" ; then
	print_notice "Enabling Lsyncd for file sync"
else
	service_stop 30-lsyncd
fi

liftoff