#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service

PROCESS_NAME="drupal"
check_service_initialized init 20-php-fpm

## DRUPAL8_WEB_DIR depreacated.
if [ ! -z "$DRUPAL8_WEB_DIR" ]; then
  DRUPAL8_WEB_DIR=${DRUPAL8_WEB_DIR:=web}
  sed -i "s/root \/var\/www\/html;/root \/var\/www\/html\/$DRUPAL8_WEB_DIR;/g" /etc/nginx/sites.enabled/drupal.conf
fi
if [ ! -z "$DRUPAL_WEB_ROOT" ]; then
  DRUPAL_WEB_DIR=${DRUPAL_WEB_ROOT:=web}
  sed -i "s/root \/var\/www\/html;/root \/var\/www\/html\/$DRUPAL_WEB_ROOT;/g" /etc/nginx/sites.enabled/drupal.conf
fi
sed -i "s/access_log  \/dev\/stdout main;//g" /etc/nginx/sites.enabled/drupal.conf
sed -i "s/unix:\/run\/php-fpm\.sock/127.0.0.1:9000/g" /etc/nginx/sites.enabled/drupal.conf




HTTP_HEADER_X_FRAME_OPTIONS=${HTTP_HEADER_X_FRAME_OPTIONS:="SAMEORIGIN"};
sed -i "s/add_header X-Frame-Options SAMEORIGIN;/add_header X-Frame-Options $HTTP_HEADER_X_FRAME_OPTIONS;/g" /etc/nginx/sites.enabled/*.conf

HTTP_HEADER_X_CONTENT_SECURITY_POLICY=${HTTP_HEADER_X_CONTENT_SECURITY_POLICY:="default-src 'self';"};
sed -i "s/add_header Content-Security-Policy \"default-src 'self';\";/add_header Content-Security-Policy \"$HTTP_HEADER_X_CONTENT_SECURITY_POLICY\";/g" /etc/nginx/sites.enabled/*.conf

# https://www.php.net/manual/en/ini.core.php#ini.variables-order
#sed -i "s/variables_order = \"GPCS\"/variables_order = \"EGPCS\"/g" /usr/local/etc/php/php.ini

# if the drupal is init by composer, the code directory locate on "web".
# This options is used to change the nginx root path.
## DRUPAL_SUBDIR support.
if [ ! -z "$DRUPAL_SUBDIR" ]; then
  DRUPAL_SUBDIR=${DRUPAL_SUBDIR:=fake-subdir-placeholder}
  sed -i "s/fake-subdir-placeholder/$DRUPAL_SUBDIR/g" /etc/nginx/sites.enabled/drupal.conf
fi

if [ ! -z "$PHP_MEM_LIMIT" ]; then
  PHP_MEMORY_LIMIT=$PHP_MEM_LIMIT
fi
# Increase the timeout
if [ ! -z "$TIMEOUT" ]; then
  PHP_TIMEOUT=$TIMEOUT
  #sed -i "s/proxy_read_timeout 60;/proxy_read_timeout ${TIMEOUT};/g" /etc/nginx/nginx.conf
  #sed -i "s/fastcgi_read_timeout 60;/fastcgi_read_timeout ${TIMEOUT};/g" /etc/nginx/nginx.conf
fi

# Increase the post_max_size
if [ ! -z "$MAX_FILE_UPLOAD_SIZE" ]; then
  #sed -i "s/post_max_size = 32M/post_max_size = ${MAX_FILE_UPLOAD_SIZE}/g" /usr/local/etc/php/php.ini
  #sed -i "s/upload_max_filesize = 32M/upload_max_filesize= ${MAX_FILE_UPLOAD_SIZE}/g" /usr/local/etc/php/php.ini
  #sed -i "s/client_max_body_size 32M;/client_max_body_size ${MAX_FILE_UPLOAD_SIZE};/g" /etc/nginx/nginx.conf
  NGINX_UPLOAD_MAX_SIZE=$MAX_FILE_UPLOAD_SIZE
  PHP_UPLOAD_MAX_SIZE=$MAX_FILE_UPLOAD_SIZE
fi

# php-fpm process related config.
if [ ! -z "$PHP_FPM_PM" ]; then
  #sed -i -E "s/pm = .*$/pm = ${PHP_FPM_PM}/g" /usr/local/etc/php-fpm.d/www.conf
  PHP_FPM_PROCESS_MANAGER=$PHP_FPM_PM
  if [ ! -z "$PHP_FPM_PM_MAX_CHILDREN" ]; then
    #sed -i -E "s/pm\.max_children = \d+$/pm.max_children = ${PHP_FPM_PM_MAX_CHILDREN}/g" /usr/local/etc/php-fpm.d/www.conf
    PHP_FPM_MAX_CHILDREN=$PHP_FPM_PM_MAX_CHILDREN
  fi

  case $PHP_FPM_PM in
    ondemand)
      #sed -i -E "s/;?pm.process_idle_timeout = .*/pm.process_idle_timeout = ${PHP_FPM_PM_PROCESS_IDLE_TIMEOUT}s/g" /usr/local/etc/php-fpm.d/www.conf;;
    dynamic)
      #sed -i \
      #  -E "s/pm.start_servers = \d+/pm.start_servers = ${PHP_FPM_PM_START_SERVERS}/g;
      #  s/pm.min_spare_servers = \d+/pm.min_spare_servers = ${PHP_FPM_PM_MIN_SPARE_SERVERS}/g;
      #  s/pm.max_spare_servers = \d+/pm.max_spare_servers = ${PHP_FPM_PM_MAX_SPARE_SERVERS}/g" \
      #  /usr/local/etc/php-fpm.d/www.conf;;
      PHP_FPM_START_SERVERS=$PHP_FPM_PM_START_SERVERS
      PHP_FPM_MIN_SPARE_SERVERS=$PHP_FPM_PM_MIN_SPARE_SERVERS
      PHP_FPM_MAX_SPARE_SERVERS=$PHP_FPM_PM_MAX_SPARE_SERVERS
  esac
fi


liftoff
