#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service

PROCESS_NAME="drupal"
check_service_initialized init 20-php-fpm
## hidden nginx version by default
echo 'server_tokens off;' > /etc/nginx/snippets/server-token-off.conf

## disable php version expose
sed -i "s#expose_php = On#expose_php = Off#g" /etc/php*/php.ini

## disable php display_errors by default.
## to enable it, PHP_DISPLAY_ERRORS = TRUE
sed -i "s#php_flag\[display_errors\] = on#php_flag\[display_errors\] = off#g" /etc/php*/php-fpm.conf

## set opcache invalidate freq 60 => 2
sed -i "s#opcache.revalidate_freq=60#opcache.revalidate_freq=2#g" /etc/php*/conf.d/00-opcache.ini

## set clear_env = no, so that the php-fpm will know env from container
# https://serverfault.com/questions/813368/configure-php-fpm-to-access-environment-variables-in-docker
sed -i -e '$a\clear_env = no' /etc/php*/php-fpm.conf

## DRUPAL8_WEB_DIR depreacated.
if [ ! -z "$DRUPAL8_WEB_DIR" ]; then
  DRUPAL8_WEB_DIR=${DRUPAL8_WEB_DIR:=web}
  sed -i "s#root \/var\/www\/html;#root \/var\/www\/html\/$DRUPAL8_WEB_DIR;#g" /etc/nginx/sites.enabled/drupal.conf
fi
if [ ! -z "$DRUPAL_WEB_ROOT" ]; then
  DRUPAL_WEB_DIR=${DRUPAL_WEB_ROOT:=web}
  sed -i "s#root \/var\/www\/html;#root \/var\/www\/html\/$DRUPAL_WEB_ROOT;#g" /etc/nginx/sites.enabled/drupal.conf
fi
sed -i "s#access_log  \/dev\/stdout main;##g" /etc/nginx/sites.enabled/drupal.conf
sed -i "s#unix:\/run\/php-fpm\.sock#127.0.0.1:9000#g" /etc/nginx/sites.enabled/drupal.conf


HTTP_HEADER_X_FRAME_OPTIONS=${HTTP_HEADER_X_FRAME_OPTIONS:="SAMEORIGIN"};
sed -i "s#add_header X-Frame-Options SAMEORIGIN;#add_header X-Frame-Options $HTTP_HEADER_X_FRAME_OPTIONS;#g" /etc/nginx/sites.enabled/*.conf

if var_true "${HTTP_HEADER_X_CONTENT_SECURITY_POLICY_ENABLE}" ; then
  ## using default value that in Dockerfile.
  ## HTTP_HEADER_X_CONTENT_SECURITY_POLICY=${HTTP_HEADER_X_CONTENT_SECURITY_POLICY:="default-src 'self';"};
  sed -i "s#add_header Content-Security-Policy \"default-src 'self';\";#add_header Content-Security-Policy \"$HTTP_HEADER_X_CONTENT_SECURITY_POLICY\";#g" /etc/nginx/sites.enabled/*.conf
else
  sed -i '/add_header Content-Security-Policy/d' /etc/nginx/sites.enabled/*.conf
fi

# https://www.php.net/manual/en/ini.core.php#ini.variables-order
#sed -i "s/variables_order = \"GPCS\"/variables_order = \"EGPCS\"/g" /usr/local/etc/php/php.ini

# if the drupal is init by composer, the code directory locate on "web".
# This options is used to change the nginx root path.
## DRUPAL_SUBDIR support.
if [ ! -z "$DRUPAL_SUBDIR" ]; then
  DRUPAL_SUBDIR=${DRUPAL_SUBDIR:=fake-subdir-placeholder}
  sed -i "s#fake-subdir-placeholder#$DRUPAL_SUBDIR#g" /etc/nginx/sites.enabled/drupal.conf
fi

if [ ! -z "$PHP_MEM_LIMIT" ]; then
  PHP_MEMORY_LIMIT=$PHP_MEM_LIMIT
fi
# Increase the timeout
if [ ! -z "$TIMEOUT" ]; then
  PHP_TIMEOUT=$TIMEOUT
  #sed -i "s/proxy_read_timeout 60;/proxy_read_timeout ${TIMEOUT};/g" /etc/nginx/nginx.conf
  #sed -i "s/fastcgi_read_timeout 60;/fastcgi_read_timeout ${TIMEOUT};/g" /etc/nginx/nginx.conf
fi

# Increase the post_max_size
if [ ! -z "$MAX_FILE_UPLOAD_SIZE" ]; then
  NGINX_UPLOAD_MAX_SIZE=$MAX_FILE_UPLOAD_SIZE
  PHP_UPLOAD_MAX_SIZE=$MAX_FILE_UPLOAD_SIZE
fi

# php-fpm process related config.
if [ ! -z "$PHP_FPM_PM" ]; then
  PHP_FPM_PROCESS_MANAGER=$PHP_FPM_PM
  if [ ! -z "$PHP_FPM_PM_MAX_CHILDREN" ]; then
    PHP_FPM_MAX_CHILDREN=$PHP_FPM_PM_MAX_CHILDREN
  fi

  case $PHP_FPM_PM in
    ondemand)
      #sed -i -E "s/;?pm.process_idle_timeout = .*/pm.process_idle_timeout = ${PHP_FPM_PM_PROCESS_IDLE_TIMEOUT}s/g" /usr/local/etc/php-fpm.d/www.conf;;
      ;;
    dynamic)
      PHP_FPM_START_SERVERS=$PHP_FPM_PM_START_SERVERS
      PHP_FPM_MIN_SPARE_SERVERS=$PHP_FPM_PM_MIN_SPARE_SERVERS
      PHP_FPM_MAX_SPARE_SERVERS=$PHP_FPM_PM_MAX_SPARE_SERVERS
      ;;
  esac
fi

liftoff
