name: Docker Image CI Debian

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        array:
          [
            {
              version: "8.3-debian",
              php_version: "8.3",
              upstream_version: "8.3-debian",
            },
          ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push to dockerhub
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          file: "Dockerfile.debian.template"
          tags: "davyinsa/docker-nginx-php:${{ matrix.array.version }}"
          build-args: |
            PHP_VERSION=${{ matrix.array.php_version }}
            UPSTREAM_VERSION=${{ matrix.array.upstream_version }}
      - name: Login to ALIYUN CR
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUNCR_USERNAME }}
          password: ${{ secrets.ALIYUNCR_PASSWORD }}
      - name: Build and push to dockerhub
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          file: "Dockerfile.debian.template"
          tags: "registry.cn-hangzhou.aliyuncs.com/davyin/nginx-php:${{ matrix.array.version }}"
          build-args: |
            PHP_VERSION=${{ matrix.array.php_version }}
            UPSTREAM_VERSION=${{ matrix.array.upstream_version }}