name: Docker Image CI

on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '30 2 * * *'
  workflow_dispatch:
    inputs:
      name:
        description: 'Reason'
        required: true
        default: 'Why??'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - 'alpine'
          #- 'debian'
        version:
          - '7.3'
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
          - '8.3'
    steps:
    - uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    -
      name: alpine Build and push
      id: docker_build_alpine
      if: ${{ matrix.arch  == 'alpine' }}
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        platforms: linux/amd64,linux/arm64
        file: '${{ matrix.version }}/${{ matrix.arch }}/Dockerfile'
        tags: 'davyinsa/docker-nginx-php:${{ matrix.version }}-${{ matrix.arch }}'
    -
      name: Debian Build and push
      id: docker_build_debian
      if: ${{ matrix.arch  == 'debian' }}
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        platforms: linux/amd64
        file: '${{ matrix.version }}/${{ matrix.arch }}/Dockerfile'
        tags: 'davyinsa/docker-nginx-php:${{ matrix.version }}-${{ matrix.arch }}'

