name: Docker Image CI

on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '30 2 * * *'
  workflow_dispatch:
    inputs:
      name:
        description: 'Reason'
        required: true
        default: 'Why??'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - 'alpine'
          #- 'debian'
        version:
          - '7.4'
          - '8.1'
          - '8.2'
          - '8.3'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          file: 'Dockerfile.${{ matrix.arch }}.template'
          tags: 'davyinsa/docker-nginx-php:${{ matrix.version }}-${{ matrix.arch }}'
          build-args: |
            PHP_VERSION=${{ matrix.version }}
