name: Docker Image CI debian bookworm

on:
  push:
    branches: [main]
  schedule:
    - cron: "30 1 * * *"
  workflow_dispatch:
    inputs:
      name:
        description: "Reason"
        required: true
        default: "Why??"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        array:
          [
            {
              php_version: "8.1",
              upstream_version: "8.1-alpine",
            },
            {
              php_version: "8.2",
              upstream_version: "8.2-alpine",
            },
            {
              php_version: "8.3",
              upstream_version: "8.3-alpine",
            },
            {
              php_version: "8.4",
              upstream_version: "8.4-alpine",
            }
          ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push to dockerhub
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          file: "Dockerfile.debian.template"
          tags: "davyinsa/docker-nginx-php:${{ matrix.array.php_version }}-debian-bookworm"
          build-args: |
            PHP_VERSION=${{ matrix.array.php_version }}
      - name: Login to ALIYUN CR
        uses: docker/login-action@v3
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUNCR_USERNAME }}
          password: ${{ secrets.ALIYUNCR_PASSWORD }}
      - name: Build and push to dockerhub
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm64
          file: "Dockerfile.debian.template"
          tags: "registry.cn-hangzhou.aliyuncs.com/davyin/nginx-php:${{ matrix.array.php_version }}-debian-bookworm"
          build-args: |
            PHP_VERSION=${{ matrix.array.php_version }}
